window.SEPHORA_PRODUCTS = {
  "one-size-oil-sucker": {
    id: "one-size-oil-sucker",
    brand: "ONE/SIZE",
    title: "Oil Sucker Liquid Blotting Paper Spray",
    breadcrumb: "Oil Sucker Liquid Blotting Paper Spray",
    price: 57,
    image: "../assets/hot-picks/one-size-oil-sucker.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 269,
    rating: 4.6,
    size: "142 mL",
    lede: "Instant mattifying spray that blots oil, blurs shine, and resets makeup. Your mid-day touch-up in a bottle.",
    whatItIs: "A liquid blotting spray inspired by blotting paper technology. Mist over makeup to absorb excess oil without disturbing your base.",
    howToUse: "Hold 8–10 inches from face. Close eyes and mist in a T-zone and chin motion. Pat lightly if needed. Reapply throughout the day.",
    whyLove: "Only at Sephora. A viral favourite for oily skin and long event days.",
    shades: null,
    tag: "new"
  },
  "laneige-juicepop-lip-tint": {
    id: "laneige-juicepop-lip-tint",
    brand: "LANEIGE",
    title: "Juicepop Box Lip Tint",
    breadcrumb: "Juicepop Box Lip Tint",
    price: 30,
    image: "../assets/hot-picks/laneige-juicepop-lip-tint.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 696,
    rating: 4.7,
    size: "Standard",
    lede: "Juicy, buildable lip tint in a playful juice-box-inspired package, with glossy colour that feels as fun as it looks.",
    whatItIs: "A lip tint with a glossy finish and comfortable, non-sticky wear. Collectible packaging makes it gift-ready.",
    howToUse: "Apply from the applicator to bare lips or over liner. Layer for more intensity. Blot once for a softer stain.",
    whyLove: "One of the newest drops on Sephora Australia, with K-beauty colour and serious staying power.",
    shades: ["08 Mocha Remix", "01 Cherry Pop", "05 Berry Burst"],
    tag: "new"
  },
  "k18-purple-shampoo": {
    id: "k18-purple-shampoo",
    brand: "K18",
    title: "Triple Bright Purple Shampoo",
    breadcrumb: "Triple Bright Purple Shampoo",
    price: 60,
    image: "../assets/hot-picks/k18-purple-shampoo.png",
    category: "Hair",
    categoryHref: "../category-hair.html",
    reviews: 233,
    rating: 4.5,
    size: "125 mL",
    lede: "Purple shampoo that fights oxidation and brass while supporting healthier-looking colour-treated hair.",
    whatItIs: "A brightening shampoo formulated to neutralise unwanted warm tones on blonde, grey, and highlighted hair.",
    howToUse: "Apply to wet hair, lather, and leave on 1–3 minutes before rinsing. Use weekly or as needed to maintain tone.",
    whyLove: "New at Sephora Australia, with salon-level toning in a travel-friendly size.",
    shades: null,
    tag: "new"
  },
  "rare-beauty-soft-pinch-blush": {
    id: "rare-beauty-soft-pinch-blush",
    brand: "Rare Beauty",
    title: "Soft Pinch Liquid Blush",
    breadcrumb: "Soft Pinch Liquid Blush",
    price: 45,
    image: "../assets/hot-picks/rare-beauty-soft-pinch-blush.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 27798,
    rating: 4.8,
    size: "7.5 mL",
    lede: "The viral weightless liquid blush. One dot delivers high-impact colour that blends seamlessly for up to 12 hours.",
    whatItIs: "A buildable liquid blush in dewy or matte finishes. Ultra-pigmented formula flatters every skin tone.",
    howToUse: "Tap one dot onto cheeks and blend with fingertips or a brush. Layer for more colour. A little goes a long way.",
    whyLove: "Only at Sephora. Sephora Australia’s most-reviewed blush for good reason.",
    shades: ["Happy", "Hope", "Joy", "Beloved"],
    tag: "hot"
  },
  "paulas-choice-bha": {
    id: "paulas-choice-bha",
    brand: "Paula's Choice",
    title: "Skin Perfecting 2% BHA Liquid Exfoliant",
    breadcrumb: "Skin Perfecting 2% BHA Liquid Exfoliant",
    price: 54,
    image: "../assets/hot-picks/paulas-choice-bha.png",
    category: "Skincare",
    categoryHref: "../category-skincare.html",
    reviews: 3135,
    rating: 4.7,
    size: "118 mL",
    lede: "The leave-on exfoliant that unclogs pores, smooths texture, and helps skin look clearer, with daily use.",
    whatItIs: "A gentle chemical exfoliant with 2% salicylic acid (BHA) for all skin types, especially combination and oily.",
    howToUse: "After cleansing, apply with a cotton pad or palms. Do not rinse. Start every other day, then increase to daily PM use.",
    whyLove: "Only at Sephora. A cult classic and top-rated exfoliant on Sephora Australia.",
    shades: null,
    tag: "hot"
  },
  "fenty-gloss-bomb": {
    id: "fenty-gloss-bomb",
    brand: "Fenty Beauty",
    title: "Gloss Bomb Universal Lip Luminizer",
    breadcrumb: "Gloss Bomb Universal Lip Luminizer",
    price: 39,
    image: "../assets/hot-picks/fenty-gloss-bomb.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 19213,
    rating: 4.8,
    size: "9 mL",
    lede: "Explosive shine that feels as good as it looks, with non-sticky gloss in shades that flatter every skin tone.",
    whatItIs: "A universal lip luminizer with shea butter and a peach-vanilla scent. The XXL wand delivers fuller-looking lips in one swipe.",
    howToUse: "Apply alone or over lipstick. Reapply as desired for extra shine.",
    whyLove: "Rihanna’s signature gloss and one of the best-selling lip products at Sephora Australia.",
    shades: ["Fenty Glow", "Fu$$y", "Heat"],
    tag: "hot"
  },
  "ouai-detox-shampoo": {
    id: "ouai-detox-shampoo",
    brand: "OUAI",
    title: "Detox Shampoo",
    breadcrumb: "Detox Shampoo",
    price: 75,
    image: "../assets/hot-picks/ouai-detox-shampoo.png",
    category: "Hair",
    categoryHref: "../category-hair.html",
    reviews: 4851,
    rating: 4.6,
    size: "474 mL",
    lede: "Deep-cleansing shampoo that removes build-up from product, hard water, and pollution, without stripping your scalp.",
    whatItIs: "A clarifying shampoo with apple cider vinegar and keratin. Leaves hair feeling fresh, light, and ready for styling.",
    howToUse: "Massage into wet hair and scalp. Rinse thoroughly. Use weekly or when hair feels weighed down; follow with conditioner.",
    whyLove: "Only at Sephora. A bestseller for reset days and post-travel hair revival.",
    shades: null,
    tag: "hot"
  },
  "fenty-pro-filtr-foundation": {
    id: "fenty-pro-filtr-foundation",
    brand: "Fenty Beauty",
    title: "Pro Filt'r Soft Matte Longwear Foundation",
    breadcrumb: "Pro Filt'r Soft Matte Longwear Foundation",
    price: 64,
    image: "../assets/face-picks/fenty-pro-filtr-foundation.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 3845,
    rating: 4.2,
    size: "32 mL",
    lede: "Soft matte foundation with climate-adaptive technology for medium to full coverage that resists heat, sweat, and shine.",
    whatItIs: "A buildable liquid foundation with a pore-diffused, shine-free finish in 50 inclusive shades.",
    howToUse: "Shake well. Apply with a brush or damp sponge and blend outward. Let matte formulas dry fully to confirm your shade match.",
    whyLove: "One of Sephora Australia's bestselling foundations for long-wear, photo-ready skin.",
    shades: null,
    tag: "hot"
  },
  "estee-double-wear-foundation": {
    id: "estee-double-wear-foundation",
    brand: "Estée Lauder",
    title: "Double Wear Stay-In-Place Foundation",
    breadcrumb: "Double Wear Stay-In-Place Foundation",
    price: 83,
    image: "../assets/face-picks/estee-double-wear-foundation.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 12000,
    rating: 4.7,
    size: "30 mL",
    lede: "Iconic 24-hour wear foundation with a natural matte finish that stays colour-true.",
    whatItIs: "Oil-free liquid foundation with medium to full coverage that looks fresh from morning to night.",
    howToUse: "Apply after primer. Blend with fingers, brush, or sponge. Build coverage where needed.",
    whyLove: "A timeless bestseller at Sephora for flawless, transfer-resistant coverage.",
    shades: null,
    tag: "hot"
  },
  "tarte-shape-tape-concealer": {
    id: "tarte-shape-tape-concealer",
    brand: "tarte",
    title: "Shape Tape Concealer",
    breadcrumb: "Shape Tape Concealer",
    price: 53,
    image: "../assets/face-picks/tarte-shape-tape-concealer.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 5510,
    rating: 4.6,
    size: "10 mL",
    lede: "Full-coverage matte concealer that smooths, brightens, and lifts the under-eye area for up to 16 hours.",
    whatItIs: "Cream concealer with tape technology to blur the look of fine lines without creasing.",
    howToUse: "Apply under eyes or over imperfections and blend upward. Set with powder for extra hold.",
    whyLove: "From the #1 concealer brand, a Sephora Australia cult favourite for all-day coverage.",
    shades: null,
    tag: "hot"
  },
  "natasha-denona-hy-glam-concealer": {
    id: "natasha-denona-hy-glam-concealer",
    brand: "Natasha Denona",
    title: "HY-Glam Concealer",
    breadcrumb: "HY-Glam Concealer",
    price: 55,
    image: "../assets/face-picks/natasha-denona-hy-glam-concealer.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 1362,
    rating: 4.5,
    size: "6 mL",
    lede: "Ultra-fluid concealer with high pigment payoff for a flawless matte finish in one stroke.",
    whatItIs: "Buildable liquid concealer that sheers or layers without patchiness on all skin types.",
    howToUse: "Use the flat side of the applicator for larger areas and the tip for spot concealing. Blend with a brush or sponge.",
    whyLove: "Pro-artist formula with an ultra-inclusive shade range, exclusive to Sephora.",
    shades: null,
    tag: "hot"
  },
  "rare-beauty-soft-pinch-contour": {
    id: "rare-beauty-soft-pinch-contour",
    brand: "Rare Beauty",
    title: "Soft Pinch Liquid Contour",
    breadcrumb: "Soft Pinch Liquid Contour",
    price: 50,
    image: "../assets/face-picks/rare-beauty-soft-pinch-contour.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 799,
    rating: 4.6,
    size: "5 mL",
    lede: "Weightless liquid contour that defines and lifts for a naturally sculpted look.",
    whatItIs: "Blendable contour that melts into skin without looking muddy or patchy.",
    howToUse: "Dot along cheek hollows, jawline, and temples. Blend with a brush or sponge while building depth.",
    whyLove: "Only at Sephora. Pairs perfectly with Soft Pinch Blush for effortless dimension.",
    shades: ["Gentle", "Mellow", "Sublime"],
    tag: "hot"
  },
  "makeup-by-mario-soft-sculpt-bronzer": {
    id: "makeup-by-mario-soft-sculpt-bronzer",
    brand: "Makeup By Mario",
    title: "Soft Sculpt Bronzer",
    breadcrumb: "Soft Sculpt Bronzer",
    price: 63,
    image: "../assets/face-picks/makeup-by-mario-soft-sculpt-bronzer.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 316,
    rating: 4.5,
    size: "Standard",
    lede: "Pressed bronzer with six neutral shades for sun-kissed warmth and soft definition.",
    whatItIs: "Lightweight powder bronzer that warms the complexion without fallout or harsh lines.",
    howToUse: "Sweep across forehead, temples, cheeks, and jawline with a fluffy brush. Layer for more depth.",
    whyLove: "Mario Dedivanovic's pro formula for a natural, second-skin bronze at Sephora Australia.",
    shades: ["Light", "Medium", "Deep"],
    tag: "hot"
  },
  "huda-easy-bake-powder": {
    id: "huda-easy-bake-powder",
    brand: "Huda Beauty",
    title: "Easy Bake Loose Powder",
    breadcrumb: "Easy Bake Loose Powder",
    price: 70,
    image: "../assets/face-picks/huda-easy-bake-powder.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 12567,
    rating: 4.8,
    size: "20 g",
    lede: "Huda's holy-grail loose powder for up to 10 hours of blurred, bake-ready perfection.",
    whatItIs: "Weightless setting powder that absorbs shine with a natural finish and no flashback.",
    howToUse: "Apply a generous layer to set makeup, bake for 3 to 5 minutes, then dust away excess.",
    whyLove: "One of the most-loved setting powders on Sephora Australia for all-day grip.",
    shades: ["Pound Cake", "Banana Bread", "Cinnamon Bun"],
    tag: "hot"
  },
  "one-size-ultimate-setting-powder": {
    id: "one-size-ultimate-setting-powder",
    brand: "ONE/SIZE",
    title: "Ultimate Setting Powder",
    breadcrumb: "Ultimate Setting Powder",
    price: 60,
    image: "../assets/face-picks/one-size-ultimate-setting-powder.png",
    category: "Makeup",
    categoryHref: "../category-makeup.html",
    reviews: 1462,
    rating: 4.3,
    size: "32 g",
    lede: "Finely milled loose powder with 24-hour shine control and a soft-focus matte finish.",
    whatItIs: "Blurring setting powder that locks makeup in place without flashback.",
    howToUse: "Press onto skin with a puff or brush. Bake under the eyes and T-zone, then brush off excess.",
    whyLove: "Patrick Starrr's go-to for full-glam hold, only at Sephora.",
    shades: ["Universal Translucent", "Ultra Peach", "Sweet Honey"],
    tag: "hot"
  }
};
